//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecarnya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptWares = new HashSet<ReceiptWares>();
        }
    
        public int Id { get; set; }
        public System.DateTime Datetime { get; set; }
        public int PriceId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptWares> ReceiptWares { get; set; }
    }
}
