//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pecarnya
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaresIngredients
    {
        public int Id { get; set; }
        public int WaresId { get; set; }
        public int IngredientsId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Wares Wares { get; set; }
    }
}
